security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
